include_guard ()

message ("NIRVANA_TARGET_PLATFORM: " ${NIRVANA_TARGET_PLATFORM})
if ("${NIRVANA_TARGET_PLATFORM}" STREQUAL "")
  set (NIRVANA_TARGET_PLATFORM ${CMAKE_SYSTEM_PROCESSOR})
endif ()

string (TOLOWER ${NIRVANA_TARGET_PLATFORM} NIRVANA_TARGET_PLATFORM)

if (${NIRVANA_TARGET_PLATFORM} STREQUAL "x64" OR ${NIRVANA_TARGET_PLATFORM} STREQUAL "amd64" OR ${NIRVANA_TARGET_PLATFORM} STREQUAL "x86_64")
  set (NIRVANA_TARGET_PLATFORM x64)
  set (NIRVANA_TARGET_ARCH "x86_64")
elseif(${NIRVANA_TARGET_PLATFORM} STREQUAL "x86" OR ${NIRVANA_TARGET_PLATFORM} STREQUAL "i386" OR ${NIRVANA_TARGET_PLATFORM} STREQUAL "i686")
  set (NIRVANA_TARGET_PLATFORM x86)
  set (NIRVANA_TARGET_ARCH "i686")
else ()
  message(FATAL_ERROR "Unsupported target platform: ${NIRVANA_TARGET_PLATFORM}")
endif ()

set (NIRVANA_TARGET_TRIPLE "${NIRVANA_TARGET_ARCH}-unknown-windows-gnu")
