name: Build Nirvana SDK

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ master, develop, feature/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # We should initialize GitFlow with '-' separators instead of '/', e.g. 'feature-'
  SDK_VERSION: "1.0.0${{ github.ref_name == 'master' && '' || (contains(github.ref_name, '/') && '-feature' || format ('-{0}', github.ref_name)) }}"
  LLVM_PATH: "${{ github.workspace }}\\llvm-release"
  NIRVANA_SDK: "${{ github.workspace }}\\out\\sdk"
  NIRVANA_TOOLS: "${{ github.workspace }}\\out\\tools-windows-x64"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    permissions:
      checks: write
      pull-requests: write

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Download LLVM
        uses: robinraju/release-downloader@v1
        with:
          repository: llvm/llvm-project
          tag: "llvmorg-21.1.0"
          fileName: clang+llvm-21.1.0-x86_64-pc-windows-msvc.tar.xz

      - name: Extract LLVM
        shell: pwsh
        run: './unpack-tar-xz.ps1 clang+llvm-21.1.0-x86_64-pc-windows-msvc llvm-release'

      - name: Pull LLVM
        run: ./pull_llvm.ps1
        shell: pwsh

      - name: Build tools
        run: ./build_tools.ps1
        shell: pwsh

      - name: Install packages
        run: ./install_packages_all.ps1
        shell: pwsh

      - name: Compile IDL
        run: ./compile_idl.ps1
        shell: pwsh

      - name: Build math library
        run: ./build_olibm_all.ps1
        shell: pwsh

      - name: Build libc++
        run: ./build_libcxx_all.ps1
        shell: pwsh

      - name: Build Nirvana
        run: ./build_nirvana_all.ps1
        shell: pwsh

      - name: Build Examples
        shell: pwsh
        run: |
          cd TestORB
          ./build.ps1
          cd ..

      - name: Run Tests
        run: ./test_all.ps1
        shell: pwsh

      - name: Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        id: test-results
        if: (!cancelled())
        with:
          files: "build/*/nirvana/test-results/*.xml"

      - name: Archive SDK
        uses: actions/upload-artifact@main
        with:
          name: "nirvana-sdk@${{ env.SDK_VERSION }}"
          path: out/sdk

      - name: Archive Tools
        uses: actions/upload-artifact@main
        with:
          name: "nirvana-tools-windows-x64@${{ env.SDK_VERSION }}"
          path: out/tools-windows-x64

      - name: Archive Core SDK
        uses: actions/upload-artifact@main
        with:
          name: "nirvana-core-sdk@${{ env.SDK_VERSION }}"
          path: out/core-sdk

      - name: Archive Sources
        uses: actions/upload-artifact@main
        with:
          name: "nirvana-sdk-sources@${{ env.SDK_VERSION }}"
          path: |
            nirvana/library/Source/
            nirvana/library/CRTL/Source/
            nirvana/orb/Source/
            llvm-project/libcxx/src/
            llvm-project/libcxxabi/src/
            llvm-project/libunwind/src/
            build/nirvana/**/*.cpp
            !build/nirvana/CMakeFiles/
            googletest/googletest/googletest/src/
